development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://:p492d60410953f64f5c1d1baa29e198be0fd7dd9a036cc84ccbdb5887f8619795@ec2-44-198-38-192.compute-1.amazonaws.com:22899
  # channel_prefix: message_rails_production
